version: '3.8'

services:
  maria:
    image: mariadb:latest
    restart: always
    container_name: currency_gateway_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: currency_gateway
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: "redis:latest"
    container_name: currency_gateway_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: currency_gateway_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  currency_gateway:
    image: buckflago/currency_gateway:latest
    container_name: currency_gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - maria
      - redis
      - rabbitmq
    environment:
      DB_CURRENCY_GATEWAY: currency_gateway_db:3306
      REDIS_CURRENCY_GATEWAY: currency_gateway_redis
      RABBIT_CURRENCY_GATEWAY: currency_gateway_rabbitmq

volumes:
  mariadb_data:
  redis_data:
  rabbitmq_data:
