spring:
  application:
    name: currency-gateway
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 4
      jdbc-url: jdbc:mariadb://${DB_CURRENCY_GATEWAY}/currency_gateway
      password: root
      username: root
  data:
    redis:
      host: ${REDIS_CURRENCY_GATEWAY}
      port: 6379
  rabbitmq:
    host: ${RABBIT_CURRENCY_GATEWAY}
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    template:
      exchange: currency-gateway-exchange
      routing-key: currency-gateway-routing-key
      default-receive-queue: currency-gateway-queue

fixer:
  base-url: http://data.fixer.io/api/
  api-key: b27dd18ebb5b542c4679ddd3ffdedf98
  update-rates-cron: 0 0 * * * *
  latest-exchanges-endpoint: latest
  currency-base-param: base
  base-currency: EUR


