spring:
  application:
    name: currency-gateway
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 4
      jdbc-url: jdbc:mariadb://localhost:3306/currency_gateway
      password: root
      username: root
  data:
    redis:
      host: localhost
      port: 6379


fixer:
  base-url: http://data.fixer.io/api/
  api-key: b27dd18ebb5b542c4679ddd3ffdedf98
  update-rates-cron: 0 * * * * *
  latest-exchanges-endpoint: latest
  currency-base-param: base
  base-currency: EUR


