version: '3.8'
services:
  maria:
    image: mariadb:latest
    restart: always
    container_name: currency_gateway_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: currency_gateway
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: